pub fn exit() -> Result<(), failure::Error> {
    Ok(())
}
